version: '3'

services:

  jenkins:
    container_name: jenkins
    build: jenkins
    hostname: jenkins
    environment:
     - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    ports:
     - "8080:8080"
    networks:
     - jenkins-nexus

  nexus:
    build: nexus
    container_name: nexus
    hostname: nexus
    ports:
     - "8081:8081"
    networks:
     - jenkins-nexus

networks:
  jenkins-nexus:
    driver: bridge
